
export const data = [
 {
   "Title": "Update home page client-side route",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/38",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 2, 2024",
   "End Date": "Oct 2, 2024",
   "Layer": "Frontend"
 },
 {
   "Title": "CI/CD initialization",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/25",
   "Story Points": 20,
   "Assignees": "crpz1",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Feature (2)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 4, 2024",
   "End Date": "Oct 6, 2024",
   "Layer": "CI/CD"
 },
 {
   "Title": "Implement Login button",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/37",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 6, 2024",
   "End Date": "Oct 6, 2024",
   "Layer": "Frontend"
 },
 {
   "Title": "Create signup page",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/36",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 7, 2024",
   "End Date": "Oct 7, 2024",
   "Layer": "Frontend"
 },
 {
   "Title": "Create signup api route",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/35",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 10, 2024",
   "End Date": "Oct 10, 2024",
   "Layer": "Backend"
 },
 {
   "Title": "Disable browser writing features",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/29",
   "Story Points": 10,
   "Assignees": "crpz1",
   "Status": "Done",
   "Labels": "bug",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 9, 2024",
   "End Date": "Oct 9, 2024",
   "Layer": ""
 },
 {
   "Title": "Fix CSS",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/48",
   "Story Points": 10,
   "Assignees": "yakobdesu",
   "Status": "Done",
   "Labels": "bug",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 13, 2024",
   "End Date": "Oct 13, 2024",
   "Layer": ""
 },
 {
   "Title": "Connect database to backend with mongoose",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/42",
   "Story Points": 20,
   "Assignees": "JosephBechara",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 3, 2024",
   "End Date": "Oct 3, 2024",
   "Layer": "Backend"
 },
 {
   "Title": "Database initialization",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/43",
   "Story Points": 20,
   "Assignees": "JosephBechara",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Sep 29, 2024",
   "End Date": "Oct 2, 2024",
   "Layer": "Database"
 },
 {
   "Title": "Create Login page",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/24",
   "Story Points": 20,
   "Assignees": "isaachannigan, yakobdesu",
   "Status": "Done",
   "Labels": "feature",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": 100,
   "Notes": "",
   "Start Date": "Oct 6, 2024",
   "End Date": "Oct 7, 2024",
   "Layer": "Frontend"
 },
 {
   "Title": "Create Leaderboard page prototype",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/34",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 11, 2024",
   "End Date": "Oct 11, 2024",
   "Layer": "Frontend"
 },
 {
   "Title": "Create scores Schema and Collection",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/33",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 10, 2024",
   "End Date": "Oct 10, 2024",
   "Layer": "Database"
 },
 {
   "Title": "Create signup client-side route",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/46",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 13, 2024",
   "End Date": "Oct 13, 2024",
   "Layer": "Frontend"
 },
 {
   "Title": "Authentication initialization",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/47",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 13, 2024",
   "End Date": "Oct 13, 2024",
   "Layer": "Database"
 },
 {
   "Title": "Create Leaderboard client-side route",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/45",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 5, 2024",
   "End Date": "Oct 5, 2024",
   "Layer": "Frontend"
 },
 {
   "Title": "Create User Schema and collection",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/44",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": 100,
   "Notes": "",
   "Start Date": "Oct 6, 2024",
   "End Date": "Oct 6, 2024",
   "Layer": "Database"
 },
 {
   "Title": "Implement Authentication on server",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/40",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 7, 2024",
   "End Date": "Oct 7, 2024",
   "Layer": "Backend"
 },
 {
   "Title": "Create \"main\" leaderboard display prototype",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/32",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 12, 2024",
   "End Date": "Oct 12, 2024",
   "Layer": "Frontend"
 },
 {
   "Title": "Implement authentication on client",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/41",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 13, 2024",
   "End Date": "Oct 13, 2024",
   "Layer": "Frontend"
 },
 {
   "Title": "Create Home page prototype",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/31",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 11, 2024",
   "End Date": "Oct 11, 2024",
   "Layer": "Frontend"
 },
 {
   "Title": "Implement logging with different logging levels on backend",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/39",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Review",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Feature (2)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": "Backend"
 },
 {
   "Title": "CI/CD integration",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/50",
   "Story Points": 20,
   "Assignees": "crpz1",
   "Status": "Done",
   "Labels": "enhancement",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Feature (2)",
   "Progress(%)": null,
   "Notes": "automatic build and deployment ",
   "Start Date": "Oct 13, 2024",
   "End Date": "Oct 13, 2024",
   "Layer": "CI/CD"
 },
 {
   "Title": "Users can Copy+Paste the prompt",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/57",
   "Story Points": 20,
   "Assignees": "yakobdesu",
   "Status": "Review",
   "Labels": "bug",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": ""
 },
 {
   "Title": "Add additional quotes for /play",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/55",
   "Story Points": 10,
   "Assignees": "yakobdesu",
   "Status": "Review",
   "Labels": "enhancement",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": ""
 },
 {
   "Title": "Fix New Game functionality and logic",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/58",
   "Story Points": 20,
   "Assignees": "yakobdesu",
   "Status": "Review",
   "Labels": "bug, enhancement",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": ""
 },
 {
   "Title": "Fix sessions not saving",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/56",
   "Story Points": 20,
   "Assignees": "isaachannigan",
   "Status": "Done",
   "Labels": "bug",
   "Linked pull requests": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/pull/59",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Fix (0)",
   "Progress(%)": 100,
   "Notes": "",
   "Start Date": "Oct 12, 2024",
   "End Date": "Oct 13, 2024",
   "Layer": "Frontend"
 },
 {
   "Title": "Implement \"main\" mode",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/17",
   "Story Points": 20,
   "Assignees": "isaachannigan",
   "Status": "Done",
   "Labels": "feature",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": 90,
   "Notes": "good enough for now",
   "Start Date": "Oct 1, 2024",
   "End Date": "Oct 6, 2024",
   "Layer": "Frontend"
 },
 {
   "Title": "Frontend initalization",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/19",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/pull/22",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 1",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Sep 25, 2024",
   "End Date": "",
   "Layer": "Frontend"
 },
 {
   "Title": "Backend intialization",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/18",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 1",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Sep 26, 2024",
   "End Date": "",
   "Layer": "Backend"
 },
 {
   "Title": "Frontend and Backend integration",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/20",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/pull/22",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 1",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Sep 27, 2024",
   "End Date": "Sep 27, 2024",
   "Layer": "Other"
 },
 {
   "Title": "Implement API route for getting logged in users information",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/61",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": 100,
   "Notes": "check-session route on login router",
   "Start Date": "Oct 13, 2024",
   "End Date": "Oct 13, 2024",
   "Layer": "Backend"
 },
 {
   "Title": "Implement profile page client-side route",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/62",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 13, 2024",
   "End Date": "Oct 13, 2024",
   "Layer": "Frontend"
 },
 {
   "Title": "Integrate game with backend and database",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/60",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "feature",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "Oct 6, 2024",
   "End Date": "Oct 6, 2024",
   "Layer": "Other"
 },
 {
   "Title": "Fix Domain Name Port",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/49",
   "Story Points": 10,
   "Assignees": "crpz1",
   "Status": "Done",
   "Labels": "bug, enhancement",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Fix (0)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": ""
 },
 {
   "Title": "Implement initial game prototype",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/21",
   "Story Points": 20,
   "Assignees": "isaachannigan",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/pull/22",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 1",
   "Priority": "Core (1)",
   "Progress(%)": 100,
   "Notes": "it works",
   "Start Date": "Sep 29, 2024",
   "End Date": "Sep 29, 2024",
   "Layer": "Frontend"
 },
 {
   "Title": "Create user profile page prototype",
   "URL": "",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Backlog",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": "Frontend"
 },
 {
   "Title": "implement subroutes for different leaderboard views",
   "URL": "",
   "Story Points": 30,
   "Assignees": "",
   "Status": "Backlog",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": "Frontend"
 },
 {
   "Title": "Implement basic logging",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/64",
   "Story Points": 10,
   "Assignees": "isaachannigan",
   "Status": "Done",
   "Labels": "feature",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Feature (2)",
   "Progress(%)": 100,
   "Notes": "using morgan for basic logging",
   "Start Date": "Oct 7, 2024",
   "End Date": "Oct 7, 2024",
   "Layer": "Backend"
 },
 {
   "Title": "fix game state bugs",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/63",
   "Story Points": 30,
   "Assignees": "isaachannigan",
   "Status": "Done",
   "Labels": "bug",
   "Linked pull requests": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/pull/30",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Fix (0)",
   "Progress(%)": 100,
   "Notes": "updated game to use useReducer hook for updating state between keystrokes",
   "Start Date": "Oct 7, 2024",
   "End Date": "Oct 12, 2024",
   "Layer": "Frontend"
 },
 {
   "Title": "Implement practice mode for logged in",
   "URL": "",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Backlog",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": "Frontend"
 },
 {
   "Title": "Implement practice mode for guests",
   "URL": "",
   "Story Points": 10,
   "Assignees": "",
   "Status": "Backlog",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": "Frontend"
 },
 {
   "Title": "Register Domain name",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/51",
   "Story Points": 10,
   "Assignees": "JosephBechara",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Feature (2)",
   "Progress(%)": 100,
   "Notes": "",
   "Start Date": "Oct 8, 2024",
   "End Date": "Oct 13, 2024",
   "Layer": "Deployment"
 },
 {
   "Title": "Point Domain name to main deployment",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/53",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Feature (2)",
   "Progress(%)": 100,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": "Deployment"
 },
 {
   "Title": "Set up SSL",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/52",
   "Story Points": 20,
   "Assignees": "crpz1",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Feature (2)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": "Deployment"
 },
 {
   "Title": "Test and verify domain",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/54",
   "Story Points": 10,
   "Assignees": "JosephBechara",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 2",
   "Priority": "Test (4)",
   "Progress(%)": 100,
   "Notes": "",
   "Start Date": "Oct 13, 2024",
   "End Date": "Oct 13, 2024",
   "Layer": "Deployment"
 },
 {
   "Title": "Implement bots",
   "URL": "",
   "Story Points": 30,
   "Assignees": "",
   "Status": "Todo",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "Feature (2)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": "Frontend"
 },
 {
   "Title": "Implement Easy, medium and hard modes",
   "URL": "",
   "Story Points": 10,
   "Assignees": "",
   "Status": "Todo",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "Feature (2)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": "Frontend"
 },
 {
   "Title": "Add sorted Texts to database",
   "URL": "",
   "Story Points": 30,
   "Assignees": "",
   "Status": "Todo",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "Feature (2)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": "Database"
 },
 {
   "Title": "Implement Api routes for sorted Texts",
   "URL": "",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Todo",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "Feature (2)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": "Backend"
 },
 {
   "Title": "Implement query for daily leaderboard",
   "URL": "",
   "Story Points": 10,
   "Assignees": "",
   "Status": "Todo",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "Feature (2)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": "Backend"
 },
 {
   "Title": "Add daily Leaderboard display to homepage",
   "URL": "",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Todo",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "Feature (2)",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": "Frontend"
 },
 {
   "Title": "Add top 5 daily to Home page",
   "URL": "",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Todo",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": ""
 },
 {
   "Title": "Live progrss bar on Play route",
   "URL": "",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Todo",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": ""
 },
 {
   "Title": "Allow custom Profile Picture",
   "URL": "",
   "Story Points": 30,
   "Assignees": "",
   "Status": "Todo",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": ""
 },
 {
   "Title": "Display Avg WPM for that difficulty",
   "URL": "",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Todo",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": ""
 },
 {
   "Title": "Display Daily rankings per person",
   "URL": "",
   "Story Points": 10,
   "Assignees": "",
   "Status": "Todo",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": ""
 },
 {
   "Title": "Implement followers feature",
   "URL": "",
   "Story Points": 40,
   "Assignees": "",
   "Status": "Todo",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": ""
 },
 {
   "Title": "Add custom bio",
   "URL": "",
   "Story Points": 10,
   "Assignees": "",
   "Status": "Todo",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": ""
 },
 {
   "Title": "Add copies of prev guest games for that session",
   "URL": "",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Todo",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": ""
 },
 {
   "Title": "Add more animations to play route",
   "URL": "",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Todo",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": ""
 },
 {
   "Title": "Check accessiblitiy (people with disablities)",
   "URL": "",
   "Story Points": 10,
   "Assignees": "",
   "Status": "Todo",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "",
   "Reviewers": "",
   "Sprint": "Sprint 3",
   "Priority": "",
   "Progress(%)": null,
   "Notes": "",
   "Start Date": "",
   "End Date": "",
   "Layer": ""
 },
 {
   "Title": "Initial Deployment",
   "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/23",
   "Story Points": 20,
   "Assignees": "",
   "Status": "Done",
   "Labels": "",
   "Linked pull requests": "",
   "Milestone": "",
   "Repository": "MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs",
   "Reviewers": "",
   "Sprint": "Sprint 1",
   "Priority": "Core (1)",
   "Progress(%)": null,
   "Notes": "galactus.bandicoot-bebop.net",
   "Start Date": "Sep 29, 2024",
   "End Date": "Sep 29, 2024",
   "Layer": "Deployment"
 }
]

