export const data = [
  {
    "Title": "Implement query for daily leaderboard",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/74",
    "Assignees": "crpz1",
    "Status": "Done",
    "Sprint": "Sprint 3",
    "Priority": "Feature (2)",
    "Story Points": "10",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 18, 2024",
    "End Date": "Oct 18, 2024",
    "Layer": "Backend"
  },
  {
    "Title": "Display Daily rankings per person",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/75",
    "Assignees": "crpz1",
    "Status": "Done",
    "Sprint": "Sprint 3",
    "Priority": "Feature (2)",
    "Story Points": "10",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 20, 2024",
    "End Date": "Oct 20, 2024",
    "Layer": "Backend"
  },
  {
    "Title": "Add daily Leaderboard display to homepage",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/72",
    "Assignees": "yakobdesu",
    "Status": "Done",
    "Sprint": "Sprint 3",
    "Priority": "Feature (2)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 18, 2024",
    "End Date": "Oct 18, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Add top 3 daily to Home page",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/73",
    "Assignees": "yakobdesu",
    "Status": "Done",
    "Sprint": "Sprint 3",
    "Priority": "",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 19, 2024",
    "End Date": "Oct 19, 2024",
    "Layer": ""
  },
  {
    "Title": "Live progrss bar on Play route",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/78",
    "Assignees": "isaachannigan",
    "Status": "Done",
    "Sprint": "Sprint 3",
    "Priority": "",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 19, 2024",
    "End Date": "Oct 20, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "add test for gameRouter",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/79",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 3",
    "Priority": "Test (4)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 19, 2024",
    "End Date": "Oct 20, 2024",
    "Layer": "CI/CD"
  },
  {
    "Title": "add tests for leaderboardRouter",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/80",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 3",
    "Priority": "Test (4)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 18, 2024",
    "End Date": "Oct 19, 2024",
    "Layer": "CI/CD"
  },
  {
    "Title": "add tests for game logic",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/81",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 3",
    "Priority": "Test (4)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 19, 2024",
    "End Date": "Oct 19, 2024",
    "Layer": "CI/CD"
  },
  {
    "Title": "Create user profile page prototype",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/67",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 3",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 17, 2024",
    "End Date": "Oct 17, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Implement different logging levels on backend",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/39",
    "Assignees": "isaachannigan",
    "Status": "Done",
    "Sprint": "Sprint 3",
    "Priority": "Feature (2)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 16, 2024",
    "End Date": "Oct 16, 2024",
    "Layer": "Backend"
  },
  {
    "Title": "implement subroutes for different leaderboard views",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/70",
    "Assignees": "",
    "Status": "Backlog",
    "Sprint": "Sprint 4",
    "Priority": "Core (1)",
    "Story Points": "30",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 22, 2024",
    "End Date": "Oct 22, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Implement practice mode for guests",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/69",
    "Assignees": "",
    "Status": "Backlog",
    "Sprint": "Sprint 4",
    "Priority": "Core (1)",
    "Story Points": "10",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 22, 2024",
    "End Date": "Oct 23, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Implement practice mode for logged in",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/68",
    "Assignees": "",
    "Status": "In Progress",
    "Sprint": "Sprint 4",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 22, 2024",
    "End Date": "Oct 23, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Update home page client-side route",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/38",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 2, 2024",
    "End Date": "Oct 2, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "CI/CD initialization",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/25",
    "Assignees": "crpz1",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Feature (2)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 4, 2024",
    "End Date": "Oct 6, 2024",
    "Layer": "CI/CD"
  },
  {
    "Title": "Implement Login button",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/37",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 6, 2024",
    "End Date": "Oct 6, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Create signup page",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/36",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 7, 2024",
    "End Date": "Oct 7, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Create signup api route",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/35",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 10, 2024",
    "End Date": "Oct 10, 2024",
    "Layer": "Backend"
  },
  {
    "Title": "Disable browser writing features",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/29",
    "Assignees": "crpz1",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "",
    "Story Points": "10",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 9, 2024",
    "End Date": "Oct 9, 2024",
    "Layer": ""
  },
  {
    "Title": "Fix CSS",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/48",
    "Assignees": "yakobdesu",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "",
    "Story Points": "10",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 13, 2024",
    "End Date": "Oct 13, 2024",
    "Layer": ""
  },
  {
    "Title": "Connect database to backend with mongoose",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/42",
    "Assignees": "JosephBechara",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 3, 2024",
    "End Date": "Oct 3, 2024",
    "Layer": "Backend"
  },
  {
    "Title": "Database initialization",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/43",
    "Assignees": "JosephBechara",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Sep 29, 2024",
    "End Date": "Oct 2, 2024",
    "Layer": "Database"
  },
  {
    "Title": "Create Login page",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/24",
    "Assignees": "isaachannigan, yakobdesu",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "100",
    "Notes": "",
    "Start Date": "Oct 6, 2024",
    "End Date": "Oct 7, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Create Leaderboard page prototype",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/34",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 11, 2024",
    "End Date": "Oct 11, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Create scores Schema and Collection",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/33",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 10, 2024",
    "End Date": "Oct 10, 2024",
    "Layer": "Database"
  },
  {
    "Title": "Create signup client-side route",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/46",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 13, 2024",
    "End Date": "Oct 13, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Authentication initialization",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/47",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 13, 2024",
    "End Date": "Oct 13, 2024",
    "Layer": "Database"
  },
  {
    "Title": "Create Leaderboard client-side route",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/45",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 5, 2024",
    "End Date": "Oct 5, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Create User Schema and collection",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/44",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "100",
    "Notes": "",
    "Start Date": "Oct 6, 2024",
    "End Date": "Oct 6, 2024",
    "Layer": "Database"
  },
  {
    "Title": "Implement Authentication on server",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/40",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 7, 2024",
    "End Date": "Oct 7, 2024",
    "Layer": "Backend"
  },
  {
    "Title": "Create \"main\" leaderboard display prototype",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/32",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 12, 2024",
    "End Date": "Oct 12, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Implement authentication on client",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/41",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 13, 2024",
    "End Date": "Oct 13, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Create Home page prototype",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/31",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 11, 2024",
    "End Date": "Oct 11, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "CI/CD integration",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/50",
    "Assignees": "crpz1",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Feature (2)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "automatic build and deployment ",
    "Start Date": "Oct 2, 2024",
    "End Date": "Oct 13, 2024",
    "Layer": "CI/CD"
  },
  {
    "Title": "Users can Copy+Paste the prompt",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/57",
    "Assignees": "yakobdesu",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 13, 2024",
    "End Date": "Oct 13, 2024",
    "Layer": ""
  },
  {
    "Title": "Add additional quotes for /play",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/55",
    "Assignees": "yakobdesu",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "",
    "Story Points": "10",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 13, 2024",
    "End Date": "Oct 13, 2024",
    "Layer": ""
  },
  {
    "Title": "Fix New Game functionality and logic",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/58",
    "Assignees": "yakobdesu",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 13, 2024",
    "End Date": "Oct 13, 2024",
    "Layer": ""
  },
  {
    "Title": "Fix sessions not saving",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/56",
    "Assignees": "isaachannigan",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Fix (0)",
    "Story Points": "20",
    "Progress(%)": "100",
    "Notes": "",
    "Start Date": "Oct 12, 2024",
    "End Date": "Oct 13, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Implement \"main\" mode",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/17",
    "Assignees": "isaachannigan",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "90",
    "Notes": "good enough for now",
    "Start Date": "Oct 1, 2024",
    "End Date": "Oct 6, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Frontend initalization",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/19",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 1",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Sep 25, 2024",
    "End Date": "Sep 25, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Backend intialization",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/18",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 1",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Sep 26, 2024",
    "End Date": "Sep 25, 2024",
    "Layer": "Backend"
  },
  {
    "Title": "Frontend and Backend integration",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/20",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 1",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Sep 27, 2024",
    "End Date": "Sep 27, 2024",
    "Layer": "Other"
  },
  {
    "Title": "Implement API route for getting logged in users information",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/61",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "100",
    "Notes": "check-session route on login router",
    "Start Date": "Oct 13, 2024",
    "End Date": "Oct 13, 2024",
    "Layer": "Backend"
  },
  {
    "Title": "Implement profile page client-side route",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/62",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 13, 2024",
    "End Date": "Oct 13, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Integrate game with backend and database",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/60",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 6, 2024",
    "End Date": "Oct 6, 2024",
    "Layer": "Other"
  },
  {
    "Title": "Fix Domain Name Port",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/49",
    "Assignees": "crpz1",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Fix (0)",
    "Story Points": "10",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 13, 2024",
    "End Date": "Oct 13, 2024",
    "Layer": ""
  },
  {
    "Title": "Implement initial game prototype",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/21",
    "Assignees": "isaachannigan",
    "Status": "Done",
    "Sprint": "Sprint 1",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "100",
    "Notes": "it works",
    "Start Date": "Sep 29, 2024",
    "End Date": "Sep 29, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Implement basic logging",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/64",
    "Assignees": "isaachannigan",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Feature (2)",
    "Story Points": "10",
    "Progress(%)": "100",
    "Notes": "using morgan for basic logging",
    "Start Date": "Oct 7, 2024",
    "End Date": "Oct 7, 2024",
    "Layer": "Backend"
  },
  {
    "Title": "fix game state bugs",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/63",
    "Assignees": "isaachannigan",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Fix (0)",
    "Story Points": "30",
    "Progress(%)": "100",
    "Notes": "updated game to use useReducer hook for updating state between keystrokes",
    "Start Date": "Oct 7, 2024",
    "End Date": "Oct 12, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Add share button on finish",
    "URL": "",
    "Assignees": "",
    "Status": "Todo",
    "Sprint": "Sprint 4",
    "Priority": "Feature (2)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 27, 2024",
    "End Date": "Oct 27, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Register Domain name",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/51",
    "Assignees": "JosephBechara",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Feature (2)",
    "Story Points": "10",
    "Progress(%)": "100",
    "Notes": "",
    "Start Date": "Oct 8, 2024",
    "End Date": "Oct 13, 2024",
    "Layer": "Deployment"
  },
  {
    "Title": "Point Domain name to main deployment",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/53",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Feature (2)",
    "Story Points": "20",
    "Progress(%)": "100",
    "Notes": "",
    "Start Date": "Oct 13, 2024",
    "End Date": "Oct 13, 2024",
    "Layer": "Deployment"
  },
  {
    "Title": "Set up SSL",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/52",
    "Assignees": "crpz1",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Feature (2)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 13, 2024",
    "End Date": "Oct 13, 2024",
    "Layer": "Deployment"
  },
  {
    "Title": "Test and verify domain",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/54",
    "Assignees": "JosephBechara",
    "Status": "Done",
    "Sprint": "Sprint 2",
    "Priority": "Test (4)",
    "Story Points": "10",
    "Progress(%)": "100",
    "Notes": "",
    "Start Date": "Oct 13, 2024",
    "End Date": "Oct 13, 2024",
    "Layer": "Deployment"
  },
  {
    "Title": "Implement bots",
    "URL": "",
    "Assignees": "",
    "Status": "Todo",
    "Sprint": "Sprint 4",
    "Priority": "Feature (2)",
    "Story Points": "30",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 22, 2024",
    "End Date": "Oct 24, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Implement Easy, medium and hard modes",
    "URL": "",
    "Assignees": "",
    "Status": "Backlog",
    "Sprint": "Sprint 4",
    "Priority": "Feature (2)",
    "Story Points": "10",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 23, 2024",
    "End Date": "Oct 24, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "Add sorted Texts to database",
    "URL": "",
    "Assignees": "",
    "Status": "Backlog",
    "Sprint": "Sprint 4",
    "Priority": "Core (1)",
    "Story Points": "30",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 23, 2024",
    "End Date": "Oct 23, 2024",
    "Layer": "Database"
  },
  {
    "Title": "Implement Api routes for sorted Texts",
    "URL": "",
    "Assignees": "",
    "Status": "Backlog",
    "Sprint": "Sprint 4",
    "Priority": "Feature (2)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 22, 2024",
    "End Date": "Oct 22, 2024",
    "Layer": "Backend"
  },
  {
    "Title": "Allow custom Profile Picture",
    "URL": "",
    "Assignees": "",
    "Status": "Todo",
    "Sprint": "Sprint 4",
    "Priority": "Feature (2)",
    "Story Points": "30",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 24, 2024",
    "End Date": "Oct 24, 2024",
    "Layer": ""
  },
  {
    "Title": "Add custom bio",
    "URL": "",
    "Assignees": "",
    "Status": "Backlog",
    "Sprint": "Sprint 4",
    "Priority": "",
    "Story Points": "10",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 26, 2024",
    "End Date": "Oct 26, 2024",
    "Layer": ""
  },
  {
    "Title": "Display Avg WPM for that difficulty",
    "URL": "",
    "Assignees": "",
    "Status": "Backlog",
    "Sprint": "Sprint 4",
    "Priority": "",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 23, 2024",
    "End Date": "Oct 23, 2024",
    "Layer": ""
  },
  {
    "Title": "Implement followers feature",
    "URL": "",
    "Assignees": "",
    "Status": "Todo",
    "Sprint": "Sprint 4",
    "Priority": "",
    "Story Points": "40",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 24, 2024",
    "End Date": "Oct 27, 2024",
    "Layer": ""
  },
  {
    "Title": "Add copies of prev guest games for that session",
    "URL": "",
    "Assignees": "",
    "Status": "Todo",
    "Sprint": "Sprint 4",
    "Priority": "",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 25, 2024",
    "End Date": "Oct 25, 2024",
    "Layer": ""
  },
  {
    "Title": "Add more animations to play route",
    "URL": "",
    "Assignees": "",
    "Status": "Backlog",
    "Sprint": "Sprint 5",
    "Priority": "",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 29, 2024",
    "End Date": "Oct 29, 2024",
    "Layer": ""
  },
  {
    "Title": "Check accessiblitiy (people with disablities)",
    "URL": "",
    "Assignees": "",
    "Status": "Todo",
    "Sprint": "Sprint 4",
    "Priority": "",
    "Story Points": "10",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 25, 2024",
    "End Date": "Oct 25, 2024",
    "Layer": ""
  },
  {
    "Title": "implement editing profile",
    "URL": "",
    "Assignees": "",
    "Status": "Todo",
    "Sprint": "Sprint 4",
    "Priority": "",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 27, 2024",
    "End Date": "Oct 27, 2024",
    "Layer": ""
  },
  {
    "Title": "implement basic user statistics",
    "URL": "",
    "Assignees": "",
    "Status": "Todo",
    "Sprint": "Sprint 4",
    "Priority": "",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 25, 2024",
    "End Date": "Oct 26, 2024",
    "Layer": ""
  },
  {
    "Title": "Initial Deployment",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/23",
    "Assignees": "",
    "Status": "Done",
    "Sprint": "Sprint 1",
    "Priority": "Core (1)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "galactus.bandicoot-bebop.net",
    "Start Date": "Sep 29, 2024",
    "End Date": "Sep 29, 2024",
    "Layer": "Deployment"
  },
  {
    "Title": "Implement better anticheat",
    "URL": "https://github.com/MQCOMP3120-2024/group-project-gwdp-monday-12pm-11-54pmdevs/issues/66",
    "Assignees": "crpz1",
    "Status": "Done",
    "Sprint": "Sprint 3",
    "Priority": "Feature (2)",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 19, 2024",
    "End Date": "Oct 20, 2024",
    "Layer": "Frontend"
  },
  {
    "Title": "migrate game logic to server side websockets",
    "URL": "",
    "Assignees": "",
    "Status": "Todo",
    "Sprint": "Sprint 5",
    "Priority": "",
    "Story Points": "40",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 30, 2024",
    "End Date": "Oct 31, 2024",
    "Layer": ""
  },
  {
    "Title": "implement frontend mock testing",
    "URL": "",
    "Assignees": "",
    "Status": "",
    "Sprint": "Sprint 5",
    "Priority": "",
    "Story Points": "30",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 28, 2024",
    "End Date": "Oct 29, 2024",
    "Layer": ""
  },
  {
    "Title": "implement full leaderboard filtering",
    "URL": "",
    "Assignees": "",
    "Status": "",
    "Sprint": "Sprint 5",
    "Priority": "",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 28, 2024",
    "End Date": "Oct 28, 2024",
    "Layer": ""
  },
  {
    "Title": "implement profile exploring for other users",
    "URL": "",
    "Assignees": "",
    "Status": "",
    "Sprint": "Sprint 5",
    "Priority": "",
    "Story Points": "20",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 28, 2024",
    "End Date": "Oct 29, 2024",
    "Layer": ""
  },
  {
    "Title": "implement friends feature",
    "URL": "",
    "Assignees": "",
    "Status": "",
    "Sprint": "Sprint 5",
    "Priority": "",
    "Story Points": "40",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Nov 1, 2024",
    "End Date": "Nov 1, 2024",
    "Layer": ""
  },
  {
    "Title": "implement daily challenge",
    "URL": "",
    "Assignees": "",
    "Status": "",
    "Sprint": "Sprint 5",
    "Priority": "",
    "Story Points": "10",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 31, 2024",
    "End Date": "Oct 31, 2024",
    "Layer": ""
  },
  {
    "Title": "implement guided typing tutorial",
    "URL": "",
    "Assignees": "",
    "Status": "",
    "Sprint": "Sprint 5",
    "Priority": "",
    "Story Points": "40",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "Oct 31, 2024",
    "End Date": "Nov 2, 2024",
    "Layer": ""
  },
  {
    "Title": "refine profile page",
    "URL": "",
    "Assignees": "",
    "Status": "Todo",
    "Sprint": "Sprint 6",
    "Priority": "",
    "Story Points": "40",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "",
    "End Date": "",
    "Layer": ""
  },
  {
    "Title": "implement head to head games",
    "URL": "",
    "Assignees": "",
    "Status": "Todo",
    "Sprint": "Sprint 6",
    "Priority": "",
    "Story Points": "50",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "",
    "End Date": "",
    "Layer": ""
  },
  {
    "Title": "implement custom head to head games",
    "URL": "",
    "Assignees": "",
    "Status": "Todo",
    "Sprint": "Sprint 6",
    "Priority": "",
    "Story Points": "50",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "",
    "End Date": "",
    "Layer": ""
  },
  {
    "Title": "implement reverse proxy",
    "URL": "",
    "Assignees": "",
    "Status": "",
    "Sprint": "Sprint 7",
    "Priority": "",
    "Story Points": "50",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "",
    "End Date": "",
    "Layer": ""
  },
  {
    "Title": "implement containerized architecture",
    "URL": "",
    "Assignees": "",
    "Status": "",
    "Sprint": "Sprint 7",
    "Priority": "",
    "Story Points": "40",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "",
    "End Date": "",
    "Layer": ""
  },
  {
    "Title": "implement horizontal scaling and load balancing",
    "URL": "",
    "Assignees": "",
    "Status": "",
    "Sprint": "Sprint 7",
    "Priority": "",
    "Story Points": "50",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "",
    "End Date": "",
    "Layer": ""
  },
  {
    "Title": "implement backup procedures",
    "URL": "",
    "Assignees": "",
    "Status": "",
    "Sprint": "Sprint 7",
    "Priority": "",
    "Story Points": "50",
    "Progress(%)": "",
    "Notes": "",
    "Start Date": "",
    "End Date": "",
    "Layer": ""
  }
]
